import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import { Outfit } from "next/font/google";
import "./styles/globals.scss";
import BoostrapClient from "./components/bootstrap";
import Header from "@/components/header/page";
import Footer from "@/components/footer/page";

const outfit = Outfit({ subsets: ["latin"], weight: ["100", "200", "300","400", "500", "600","700","800","900"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <Header />
        {children}
        <Footer />
      </body>
      <BoostrapClient />
    </html>
  );
}
